FROM ubuntu:22.04

# 1. Préparation de l'environnement
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    htop \
    curl \
    && rm -rf /var/lib/apt/lists/*

# 2. Configuration utilisateur et dossier
WORKDIR /home/game/server
RUN mkdir -p bin scripts data

# 3. Personnalisation (MOTD)
RUN echo "Bienvenue sur le Cloud Game Server" > /etc/motd && \
    echo "cat /etc/motd" >> /root/.bashrc

# 4. Copie du script de démarrage
COPY ./start-game.sh /usr/local/bin/start-game.sh
RUN chmod +x /usr/local/bin/start-game.sh

# 5. Réseau
EXPOSE 25565

# 6. Point d'entrée gérant le cycle de vie
ENTRYPOINT ["/usr/local/bin/start-game.sh"]